version: '3'

services:
  master:
    build: .
    ports:
      - "8089:8089"
    volumes:
      - /Locust/locustfiles:/mnt/locust
    command: -f /mnt/locust/demo.py --master -H http://master:8089

  worker:
    image: docker-compose_master
    volumes:
      - /Locust/locustfiles:/mnt/locust
    command: -f /mnt/locust/demo.py --worker --master-host master
